name: vinttem_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.9

dependencies:
  bloc: ^8.1.1
  brasil_fields: ^1.9.1
  build_runner: ^2.3.3
  equatable: ^2.0.5
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  go_router: ^7.1.1
  intl: ^0.17.0
  json_annotation: ^4.8.1
  multi_select_flutter: ^4.1.3
  vinttem_repository:
    path: packages/vinttem_repository

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  melos: ^3.0.1
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  test: ^1.0.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
