name: vinttem_app
description: A new way of tracking expenses that considers how much each person earns.
version: 1.0.0+6
publish_to: none

environment:
  sdk: ">=3.0.1"
  flutter: 3.10.1

dependencies:
  bloc: ^8.1.1
  brasil_fields: ^1.9.1
  build_runner: ^2.4.4
  equatable: ^2.0.5
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.0
  go_router: ^7.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  network_client:
    path: packages/network_client
  vinttem_repository:
    path: packages/vinttem_repository
  vinttem_ui:
    path: packages/vinttem_ui

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  melos: ^3.1.1
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  test: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
