include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    one_member_abstracts: false
analyzer:
  exclude: [lib/**/*.g.dart]